### PR TITLE
Bugfix version argument not working (#190)

### LINKED ISSUE #190: Command line option -v doesn't return version and pom version id & MANIFEST.MF still at 3.2.2
running java -jar sonar-cnes-report-3.3.0.jar -v 
Results in:
[ERROR] Please provide a project with the -p argument, you can also use -h argument to display help.

Running with -v -p MyProject also results in Error
[ERROR] Illegal command line arguments

Furthermore, the version tag in META-INF/MANIFIEST.MF and in
META-INF/maven/fr.cnes.sonar/cnesreport/pom.xml
Shows 3.2.2

Binary artifact sha1sum is: 97493f995ba669bf686e08c323e51790f5e74ff3

### PR DESCRIPTION
**Pull request by ErwanGauduchon**
## Proposed changes

Fix the issue when using -v option.

This follows #190: before this change, the version argument was not recognized as a standalone option and it wasn't possible to retrieve the value of the current version.

## Types of changes

What types of changes does your code introduce to this software?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Issues closed by changes

- [x] Close #190 

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/cnescatlab/sonar-cnes-report/blob/master/CONTRIBUTING.md) doc
- [x] I agree with the [CODE OF CONDUCT](https://github.com/cnescatlab/sonar-cnes-report/blob/master/CONTRIBUTING.md)
- [x] Lint and unit tests pass locally with my changes
- [x] SonarCloud and Travis CI tests pass with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/main/java/fr/cnes/sonar/report/utils/CommandLineManager.java [hunk 1]
```diff
@@ -112,6 +115,19 @@ public void parse(final String[] pArgs) {
...
             printHelp();
             System.exit(0);
+        } else if (commandLine.hasOption("v")) {
+            // Display version information and exit.
+            try(InputStream input = this.getClass().getClassLoader().getResourceAsStream("version.properties")) {
+                if(input!=null) {
+                    final Properties properties = new Properties();
+                    properties.load(input);
+                    String version = properties.getProperty("version");
+                    LOGGER.info(version);
```
Comment (Sancretor) [inline src/main/java/fr/cnes/sonar/report/utils/CommandLineManager.java:125]: Replace log method by a simple message text on the standard output

**Review by Sancretor — CHANGES_REQUESTED** [review]

**Review by Sancretor — APPROVED** [review]
