### PR TITLE
Fix duplicate API call in plugin webpage initialization (#213)

### LINKED ISSUE #213: Duplicate call to API in plugin web page initialization
#### Describe the bug

When you load the plugin page in a web browser, you could see two similar GET requests.
We should have a look at that, to be sure we don't do multiple useless API requests.

#### To reproduce

1. Open your web browser network screen
2. Open the plugin web page

#### Expected behavior

A minimal amount of requests should be used, no more.

#### Screenshots & log

image

### PR DESCRIPTION
**Pull request by ErwanGauduchon**
## Proposed changes

Fix a duplicate API call when loading the plugin webpage.
This follows #213: before this change, two requests giving the same result were executed in a row.

## Types of changes

What types of changes does your code introduce to this software?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Issues closed by changes

- [x] Close #213 

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/cnescatlab/sonar-cnes-report/blob/master/CONTRIBUTING.md) doc
- [x] I agree with the [CODE OF CONDUCT](https://github.com/cnescatlab/sonar-cnes-report/blob/master/CONTRIBUTING.md)
- [x] Lint and unit tests pass locally with my changes
- [x] SonarCloud and Travis CI tests pass with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/main/js/common/api.js [hunk 1]
```diff
@@ -21,11 +21,15 @@ export function getProjectsList(){
...
     let nbPages = Math.ceil(nbProjects/elementByPage);
-    //Fill an array of promises
-    for(let i = 1; i <= nbPages; i++){
-      allPromises.push(getJSON("/api/components/search", {"qualifiers": "TRK", "ps":elementByPage, "p":i}).then(response => {
-        return response.components;
-      }));
+    //Store the first page
+    allPromises.push(response.components);
+    //Fill the array of promises with next pages if there are ones
+    if (nbPages >= 2) {
```
Comment (Sancretor) [inline src/main/js/common/api.js:27]: I wonder if this `if` is really useful, since the `for` loop won't run if nbPages is not superior or equal to 2.
What do you think ?

**Review by Sancretor — APPROVED** [review]
