### PR TITLE
Fix wrong colors in docx report charts

### LINKED ISSUE #166: Pie chart colors specified in custom template are incorrect
#### Describe the bug

It appears that colors specified in a template for the pie chart won't stay consistent. For example, if I set it up like so in the template:
image

The colors appear to "shift" one to the left. So that BLOCKER is green, CRITICAL is black, and so on.

#### To reproduce

1. Create custom template with LibreOffice
2. Modify the chart colors
3. Create report on CLI using this template
4. Observe mismatched colors

#### Expected behavior

Colors line up with severity levels as specified in the template

#### User environment 

* OS: Ubuntu 20.04
* Project version: 3.2.2
* SonarQube: 8.4

### PR DESCRIPTION
**Pull request by ErwanGauduchon**
## Proposed changes

Fix color assignment in docx report pie charts.
This follows #166: before this change, the colors specified in the template were not respected.

## Types of changes

What types of changes does your code introduce to this software?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Issues closed by changes

- [x] Close #166 

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/cnescatlab/sonar-cnes-report/blob/master/CONTRIBUTING.md) doc
- [ ] I agree with the [CODE OF CONDUCT](https://github.com/cnescatlab/sonar-cnes-report/blob/master/CONTRIBUTING.md)
- [ ] Lint and unit tests pass locally with my changes
- [ ] SonarCloud and Travis CI tests pass with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Sancretor — CHANGES_REQUESTED** [review]

File: src/main/java/fr/cnes/sonar/report/exporters/docx/DataAdapter.java [hunk 1]
```diff
@@ -460,9 +464,28 @@ private DataAdapter(){}
             }
         }
 
+        // sort the result to fit docx template lengends
```
Comment (Sancretor) [inline src/main/java/fr/cnes/sonar/report/exporters/docx/DataAdapter.java:467]:
```suggestion
        // sort the result to fit docx template legends
```

File: src/main/java/fr/cnes/sonar/report/exporters/docx/DataAdapter.java [hunk 2]
```diff
@@ -809,6 +832,33 @@ public int compare(String o1, String o2) {
             );
         }
 
+        return compare;
+    }
+}
+
+/**
+ * ValueComparator is used to compare 2 values to sort them by severity or type
```
Comment (Sancretor) [inline src/main/java/fr/cnes/sonar/report/exporters/docx/DataAdapter.java:840]:
```suggestion
 * ValueComparator is used to compare 2 facets to sort them by severity or type
```

File: src/main/java/fr/cnes/sonar/report/exporters/docx/DataAdapter.java [hunk 3]
```diff
@@ -809,6 +832,33 @@ public int compare(String o1, String o2) {
...
+ */
+class ValueComparator implements Comparator<Value>{
```
[the remark this answers is not in the document]
Comment (Sancretor) [reply src/main/java/fr/cnes/sonar/report/exporters/docx/DataAdapter.java:842]: "Value" is also a generic word, it would better to designate it as Facet, don't you think ?

**Review by Sancretor — CHANGES_REQUESTED** [review]

**Review by Sancretor — APPROVED** [review]
